### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by swagween** [cpp-gamedev/spaced#10]
Add a small `Color` struct to create a palette for the game using `bave::Rgba`. Colors should include:

sp_black_v{0x231d2aff};
sp_milk_v{0xe5cdaeff};
sp_grey_v{0x535151ff};
sp_mocha_v{0x6f5a48ff};
sp_ice_v{0xd6dbe1e1};

To be changed and others to be added as needed. Should be accessible pretty much everywhere.

**Comment by karnkaul** [comment]
Some upgrades:
1. It should be data driven: this will allow theming and modding. In code it could be a map of string => Rgba.
1. We should add this to the existing `Styles` [service](https://github.com/cpp-gamedev/spaced/blob/main/src/spaced/spaced/services/styles.hpp).
